### ISSUE TITLE
Maven repo / mvnosgi broken

### ISSUE THREAD

**Issue by maggu2810** [ctron/package-drone#101]
... continue of #93
I looked at an old channel with mvnosgi artifacts, they are still present.
After I pressed on "refresh aspects" the mvnosgi artifacts are lost in the Maven repo.
The Maven repo is empty, but I have no POMs in the channel, so I do not know if you broke mvnosgi or the whole maven repo.

**Comment by ctron** [comment]
You mean from 0.9.0 to 0.9.1?

**Comment by maggu2810** [comment]
78760ca70423cf4d688999a725a0a29ca2234d1f

**Comment by maggu2810** [comment]
Sorry, I mean from last one I used till this one I used.
before (working): ?? With 0.9.0 or 0.9.1 it was working
now (broken): 78760ca70423cf4d688999a725a0a29ca2234d1f

Have I to bisect?

**Comment by ctron** [comment]
I fear so ... I just made 0.9.2, which has its own release branch, `0.9.x-release`. And should contain only a subset of changes on `master`. Maybe this already cuts it down.

I am not aware of any changes done for mvnosg, so the problem could be within the MavenServlet.

**Comment by afischer211** [comment]
May be the releases 0.9.x should be stabilized before publishing the next big release 0.10.0?
Can I install the fix-version 0.9.2 (see isue #100 ) without further impact on this topic?

**Comment by maggu2810** [comment]
I will edit this post until I found it...

working:
* 771dd50ae2ddc51d830ab55adac8705ad95ea89f 

not working:
* 78760ca70423cf4d688999a725a0a29ca2234d1f

**Comment by ctron** [comment]
That is why I made a branch for 0.9.x ... 

This release 0.9.2 only contains the changes for #97 and #100. The test cases and the integration tests passed. However since it was a quick release, there a higher risk than usual.

**Comment by afischer211** [comment]
Ok, but I assume, that the 0.9.2 version is not more faulty than 0.9.1. So I will install 0.9.2 and look forward...

**Comment by maggu2810** [comment]
If I bisected and tested correctly:

<pre>
b3aedeeb1d89284298c42f7c7a8b71e9ed55cbe8 is the first bad commit
commit b3aedeeb1d89284298c42f7c7a8b71e9ed55cbe8
Author: Jens Reimann <jens.reimann@ibh-systems.com>
Date:   Thu May 28 15:24:15 2015 +0200

    add support for processing RPM file and creating a YUM repository, #16

:040000 040000 ebd7d1685b167d4683ae643579363cf0e3d4c378 dc8ad8266a6ce7d63b9c4320053d06330f670bdc M      de.dentrassi.pm.aspect.common
:040000 040000 5e937ca8919bbc8ff72c758fc5209dab71f929c4 9cb522221eb2fa433e1b338ebcbe4db86e5830cb M      de.dentrassi.pm.aspect
:040000 040000 15ba4cf0d6f563da06ac472d5751f2698931d4d0 264bdb76ac65cf1128f1a655a4aa5d9bb7ba6f2d M      de.dentrassi.pm.common
:040000 040000 69d896fcb6297fae39ba99dc7349b1b3540cd232 9b9a1385fbd488ffedf181f3b065189434e6b84f M      de.dentrassi.pm.deb
:040000 040000 a1381da592b9f29b01bf991b4a05c3aca61ba8d7 2ebfdcef1bad4f322a72bf385d13707f415ffaea M      de.dentrassi.pm.maven
:040000 040000 75e3a6d65da7eb6f94931ac30c5f49c57d291ff0 825b26987ecde09766bc563d6cd8a0dc5fdb9fb2 M      de.dentrassi.pm.p2
:000000 040000 0000000000000000000000000000000000000000 f590386bd5ce61646ee8c6f3895bafc8ba5b7d8d A      de.dentrassi.pm.rpm
:040000 040000 dca56fe60ceb51fed0c0e6598c2a5ea904dc1103 94078ce57f2d6123210e7b6842ac753039f1d820 M      de.dentrassi.pm.storage.service.jpa
:040000 040000 ce4f67fffd96d4db9b8242ffa7440d3b2eec0c8e 5773d640d9168900dcb5f49c7ddaeaad728f5f19 M      de.dentrassi.pm.storage.web
:040000 040000 7a892059d75230c8d3538d01a25a09f24fc9db24 b5ac50c0d7d7221514dd764ed3c8cfeb0f42623e M      de.dentrassi.pm.storage
:000000 040000 0000000000000000000000000000000000000000 2eb7c895af4fb2a0acdc221b58d5bf92a8ae9388 A      de.dentrassi.rpm.tests
:000000 040000 0000000000000000000000000000000000000000 7e1e29c1e9e289955731a97041a5b20772e423db A      de.dentrassi.rpm
:000000 040000 0000000000000000000000000000000000000000 0b258bc4394d0836079d8c7ada0483c98b0aa104 A      org.tukani.xz
:040000 040000 6b1777a40acfd04ea01d1977b4799cf23cc9acce 5765922e875f8b9054efe3a6e5ee9193b40577e2 M      runtime
</pre>

**Comment by ctron** [comment]
So I could only imagine that:

```
@@ -138,6 +138,7 @@
         final DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance ();
         try
         {
+            dbf.setNamespaceAware ( true );
             this.db = dbf.newDocumentBuilder ();
         }
         catch ( final ParserConfigurationException e )
```
would cause troubles.

Most other changes in this commit seem either irrelevant or ok.

Do you have a channel export?

**Comment by ctron** [comment]
Ok, when the `MavenInformationExtractor` tries to read out the POM file information it seems not to find the GAV elements.

**Comment by ctron** [comment]
Commenting out:

```java
// this.dbf.setNamespaceAware ( true );
```

restores the functionality

**Comment by maggu2810** [comment]
You could reproduce it in a simple way:

* git checkout f67e9f3
* rebuild using Eclipse IDE
* start using Eclipse launch config
* create new channel
* edit, configure aspects, add: mvnosgi (with dependencies)
* add an OSGi jar using "drop artifacts" (used: de.dentrassi.pm_0.9.0.20150520-0903.jar)
* click on "Maven Repository" and see the mvnosgi group there
* stop Package Drone in the Eclipse IDE

* git checkout b3aedee
* rebuild using Eclipse IDE
* start using Eclipse launch config
* create new channel
* edit, configure aspects, add: mvnosgi (with dependencies)
* add an OSGi jar using "drop artifacts" (used: de.dentrassi.pm_0.9.0.20150520-0903.jar)
* click on "Maven Repository" and __DO NOT__ see the mvnosgi group there
* stop Package Drone in the Eclipse IDE

**Comment by ctron** [comment]
Seems to be a form of: https://stackoverflow.com/questions/6760343/xpath-returning-null-for-node-when-isnamespaceaware-and-isvalidating-are-true

**Comment by ctron** [comment]
I fixed the issue in 823a725e255aa8c9bc7ce4f5afb63ecc95ea05a2, which effectively reverts back to uses "non-namespace aware" documents and adds methods to explicitly request them when necessary.

**Comment by ctron** [comment]
It is definitely time for more test cases!

**Comment by ctron** [comment]
The test case validates the fix!

**Comment by maggu2810** [comment]
Good, can't check it for myself niw. Will have to wait for tomorrow.

**Comment by ctron** [comment]
I will make another 0.9.x release tomorrow which contains the fix.

**Comment by maggu2810** [comment]
I thought the problematic commit was not part of the 0.9.x branch

**Comment by ctron** [comment]
That's what I thought at first, but I checked and it got piggy backed on a cherry pick. So I will make a 0.9.3 today and continue writing integration tests :wink:

**Comment by ctron** [comment]
Is this closed from your point of view?

**Comment by maggu2810** [comment]
Tried to test the current master.
Using the master branch the Eclipse IDE complains about missing constraints (javax.mail and com.sun.mail.handlers).
Ignoring this message results in a lot of errors in the console.

**Comment by ctron** [comment]
You need to re-run the runtime ant script and reload the target platform.

**Comment by maggu2810** [comment]
Thank you, it is working again.
