### ISSUE TITLE
bad generated p2-metadata

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#102]
I have uploaded an eclipse-feature over the web-interface (drg&drop).
In the features-view from the pdrone web-gui the feature is correctly displayed with included plugins, included features and requirements.
If I look into the content.xml file (p2-view for the channel), the required plugins are listed as required features?!
Here the feature-details from the web-gui:
![image](https://cloud.githubusercontent.com/assets/4056990/7935162/ea5df1fc-092e-11e5-8404-0fc9033d4a2d.png)

And here the fragment of content.xml with bad requirements (feature.group instead of the plugin):
![image](https://cloud.githubusercontent.com/assets/4056990/7935205/4f697daa-092f-11e5-9a80-6781a40adf7e.png)

And at last the content-fragment of feature.xml with defined requirements:
`
   <requires>
      <import plugin="org.eclipse.osgi"/>
      <import plugin="org.apache.commons.beanutils" version="1.8.0" match="perfect"/>
      <import plugin="org.apache.commons.collections" version="3.2.1" match="perfect"/>
      <import plugin="org.apache.commons.digester" version="2.0.0" match="perfect"/>
      <import plugin="org.apache.commons.lang" version="2.5.0" match="perfect"/>
      <import plugin="org.apache.commons.io" version="2.0.1" match="perfect"/>
      <import plugin="org.apache.commons.net" version="2.0.0" match="perfect"/>
      <import plugin="org.apache.commons.logging" version="1.1.1" match="greaterOrEqual"/>
      <import plugin="org.apache.commons.lang3" version="3.1.0" match="perfect"/>
   </requires>
`

**Comment by afischer211** [comment]
The from package-drone auto-generated (and attached as child within repository) file p2metadata.xml has the same errors (requirements for features instead of plugins).
Are the any problems with the corresponding aspect "**P2 Metadata Generator 1.0.0 – p2.metadata**"? What is the decision-base for requirements to bundles or features?

**Comment by afischer211** [comment]
After some retries the following new informations:
The p2-metadata generation seems to generate for every requirement an entry with the id as feature (.feature.group attached) and as bundle (original id). But the reference to the bundle only occurs, if the bundle with the same id **is already located** in this channel. If the bundle is not present, then only the reference to the feature is generated.
So, if I deploy a feature and later deploy the required bundles, the metadata for the feature are corrupted (bad or missing requirements).

**Comment by ctron** [comment]
I am just checking this.

**Comment by ctron** [comment]
Now that was a stupid one!

**Comment by afischer211** [comment]
Will you build a new yum-package for 0.9.3?

**Comment by ctron** [comment]
I will .. but I would like to make a test case first.

**Comment by ctron** [comment]
I uploaded the signed release rpm to the wuala folder.

**Comment by afischer211** [comment]
The p2-metadatas for features are correct again with version 0.9.4. I have reload all aspects for the channels for getting correct metadatas again.
