### ISSUE TITLE
Big log-file for eclipse-link

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#118]
On my running instance of PDrone 0.10.1 against a PostgreSQL database I detected a growing logfile **/tmp/eclipselink.log**. In this file different sql-queries are logged.
How can I configure or reduce this logging?

**Comment by ctron** [comment]
You can't. And it should never have been active in production. :(

I will make a new version tomorrow which will disable this. Sorry!

**Comment by afischer211** [comment]
Ok, thanks for the fix. I will wait for the new version.

**Comment by afischer211** [comment]
With the new version **0.10.2** the logfile **eclipselink.log** does not occur anymore.
