### ISSUE TITLE
Startup-Script init.d for debian (wheezy)

### ISSUE THREAD

**Issue by SneipasOmoH** [ctron/package-drone#119]
Hello there,
i have installed the latest debian package of the drone and as far as i see, everything works so far, except the starting as a service. There is no startup-script in /etc/init.d/ to manage it after the installation, or i haven't found it yet. Therefore i need some help or a hint to get it fixed. I tried one i found in the source package, but it doesn't work with wheezy.

Thank's a lot,
Michael

**Comment by ctron** [comment]
This is true. There is currently no startup script for Debian only for Ubuntu,

**Comment by SneipasOmoH** [comment]
Ok. Thanks for the quickest response i ever experienced :-) Then i will try to fix it by myself, and if i get it done, i will contribute it to the drone, if welcome. Could take some time...
Greetings,
Michael

**Comment by ctron** [comment]
Every help is welcome! :wink: 

Thanks!

**Comment by SneipasOmoH** [comment]
Till then....

**Comment by SneipasOmoH** [comment]
Hello ctron,
i wrote the init-script to manage the launch of the drone on systemstart and manage it after. It's written for wheezy and is testet on my debian-server. I took the base from debians init.d/skeleton for it. One issue i have, is the missing (or for me unknown) returncode to detect the successfull or failed start of the drone-service and react appropriate, so i choose the poor (and actually unwanted) sleep 10 seconds-method in the script to wait for the service. In my tests the script worked fine, the start after rebooting the server, the "start | stop | restart | status" - thing also works well. In my system i made some adjustments to the original drone-installation. I set the owner and the group-settings below /usr/lib//usr/lib/package-drone-server to pdrone:pdrone, renamed the executable from "server" into "pgdrone", the skript itself starts the drone-service as pdrone:pdrone. In my tests i experienced no problems with this configuration, but if this is a problem however, it should be easy to suite the init-script. I don't tink, the script is the last state of the art of progamming an init-script, but it's a base to start from. So want contribute it to the project, wehre can i upload it or send to?
Greetings,
Michael

**Comment by ctron** [comment]
The easiest way is a github pull request. We could then work on the details.

**Comment by SneipasOmoH** [comment]
Ok,
i will launch a pull request, after i've read the guidlines. I am new in this business :-)
Till then...

**Comment by ctron** [comment]
If you need any help, just let me know :)
