### ISSUE TITLE
OSGi R5 aspect does not respect "resolution :=optional" on requirements

### ISSUE THREAD

**Issue by JFingerle** [ctron/package-drone#126]
My bundle has the following manifest section:
```
Bundle-SymbolicName: de.my.bundle
Import-Package: resolution:=optional,de.my.package
```
The R5 OBR index entry for this bundle looks like this:
```
<resource>
   <capability namespace="osgi.identity">
      <attribute name="osgi.identity" value="de.gebit.trend.integrity"/>
      <attribute name="type" value="osgi.bundle"/>
      <attribute name="version" type="Version" value="1.0.0"/>
  </capability>
   ...
   <requirement namespace="osgi.wiring.package">
      <directive name="filter" value="(osgi.wiring.package=de.my.package)"/>
   </requirement>
</resource>
```
Please note that in the R5 OBR index the requirement is not listed as optional.
It should look like this:
```
<requirement namespace="osgi.wiring.package">
   <directive name="filter" value="(osgi.wiring.package=de.my.package)"/>
   <directive name="resolution" value="optional"/>
</requirement>
```

**Comment by JFingerle** [comment]
I added a pull request #127 which should fix this. Please check and merge.

**Comment by JFingerle** [comment]
I just used the change from pull request #127 to release 0.10.3. This is fixing the described issue. The R5 OBR index now looks like this:
```
<requirement namespace="osgi.wiring.package">
   <directive name="filter" value="(osgi.wiring.package=de.my.package)"/>
   <directive name="resolution" value="optional"/>
</requirement>
```

**Comment by ctron** [comment]
This sounds great! :+1: 

So I guess it will be time for a 0.10.4 version.

**Comment by ctron** [comment]
Ok, since we are preparing to contribute the project to the Eclipse Foundation, could you print, sign, scan and e-mail me the CLA (https://github.com/ctron/package-drone/wiki/Contributor-License-Agreement) so that we can submit it with the initial code review. You can send it to my e-mail address.

**Comment by JFingerle** [comment]
I will mail you the CLA tomorrow, no problem.

**Comment by ctron** [comment]
Ok, cool.
