### ISSUE TITLE
0.11.0-m1: All missing...

### ISSUE THREAD

**Issue by maggu2810** [ctron/package-drone#134]
In the release notes you have written:

> all data is not stored in the local filesystem of the server.

I think you should change "not" in "now". :)

So, but my problem:
I unzipped the archive to a new directory and start the server.
The only thing I can do is to setup a mail account. How do I create an user? How do I create channels?

**Comment by ctron** [comment]
True, this documentation fix was easy :wink: 

Yes, there is one step missing in the M1, the setup of the storage location. Which can be done by using a system property. Again a documentation issue.

But actually I did plan on making a M2 this week, which has the necessary UI ready for an initial setup when using the ZIP variant. Actually the DEB and RPM do set the storage location automatically.

**Comment by maggu2810** [comment]
User management (add a new one) missing on this milestones or a missing property, too?

Thank you for your work. :+1:

**Comment by ctron** [comment]
The user management is also based on the new storage manager. When the channels are available, the users should be available as well.
