### ISSUE TITLE
Uploading a zipped p2-repository fails

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#138]
I try to upload a zipped p2-repository (Eclipse Babel) into a new channel for using as a p2-repository for tycho-builds. My works fails for external zip-archives, but another small zip-archive downloaded from pdrone (channel -> p2 by ID -> repo.zip) works by uploading over drag&drop. So I have some questions:
* How can I upload big (>100mb) zip-archives?
* What are the correct settings for the channel (which aspects should be enabled and which not)?
* What is the correct structure of the zip-archive (should the **artifacts.xml** and **content.xml** uncompressed and situated in the root of the zip-archive)?

**Comment by ctron** [comment]
Well, the Babel ZIP file does contain a sub-directory where the actual P2 data is loaded. I saw this myself when testing with Babel.

Right now it is expected that the P2 ZIP has a `features` and `plugins` folder at the root.

**Comment by ctron** [comment]
The question is how the logic could be enhanced to process files like this in addition.

**Comment by ctron** [comment]
Uploading big file works best using the "Add" button in the channel. The drag and drop way struggles with big files on the browser side. I guess this has something to do how Dropzone handles this process.

**Comment by afischer211** [comment]
Ok, with this informations I can try again...

**Comment by afischer211** [comment]
Ok, a test with a orbit-download (>300mb) was successful. Many thanks for your hints.
