### ISSUE TITLE
not-working resolution of manifest-values from plugin.properties

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#140]
If I have an OSGi-bundle, where some variables are used in the Manifest (eg. %vendor) and the value for the variables is defined in a file **/plugin.properties** (at root of the jar-file), all is ok - if (and only if) the file is named **plugin.properties** and the entry **Bundle-Localization: plugin** is contained in the manifest.
I think, in regular p2-repositories the manifest-variables (not other variables in "plugin.xml" or so) are resolved also without the entry inside the manifest.
One not working example is the bundle **com.google.guava** at version **10.0.1.v201203051515**.
If I add manually a file "plugin.properties" to the root of the jar and also the entry into the manifest, the resolution works.

**Comment by ctron** [comment]
Closing this one in the favor of eclipse/packagedrone#2

**Comment by afischer211** [comment]
Hello,

can you provide a patch for the 0.11.x-release? We get many warning messages on Maven-console, because in the content.xml exists non-resolved variables (%var-entries).

**Comment by ctron** [comment]
Yes. I will try to get it out today or tomorrow.

**Comment by afischer211** [comment]
The resolving of property-variables works again, many thanks!

**Comment by ctron** [comment]
Thanks for reporting!
