### ISSUE TITLE
Deployment with another user (only can be deploy with deploy user)

### ISSUE THREAD

**Issue by guel135** [ctron/package-drone#145]
Hello, 
First of all, thank you for package drone is a tool that help us a lot in our company making the things easier. 
In our company we use generated code and when we develop new things we use a codegen-staging channel. 
We wanted to have another different user to make this staging channel working with our proxy that also requires authentication and we can only pass it having the same user and password in booth sides invalided us to use the same user with several passwords. 

We dont want to expose the deployment key for all the developers since we work with external developers.
Many thanks for your help and it is only a improvement for us that not need to be quick. And also will be a lot more important features.

Keep making this good work.

**Comment by ctron** [comment]
Thank you for the positive feedback :+1:

So the proxy also requires HTTP basic authentication?

Could you open the issue in the repository eclipse/packagedrone since this is the older repository for pre-0.12.x releases. Thanks.

**Comment by guel135** [comment]
Sorry, if I make in the incorrect one. I will make it there.
