### ISSUE TITLE
Resource could not be found

### ISSUE THREAD

**Issue by chainwu** [ctron/package-drone#151]
Hi 
I tried to upload a file to an APT repository by using curl

curl -X PUT --data @build.sh http://deploy:xxxxx@10.6.109.2:8080/api/v3/upload/channel/9781C604-0952-47BF-B76D-6A45E694B792/build.sh

I can confirm that the password and channel id are both correct, but no matter how I tried, it always complains:

Resource '/api/v3/upload/channel/9781C604-0952-47BF-B76D-6A45E694B792/build.sh' could not be found

Is there a log in the system where I can check or is there anything wrong with my command?

The version is "Package Drone 0.10.4.20150930-0816"

**Comment by ctron** [comment]
Please note that the Upload V3 API is only available in Package Drone 0.14.0, see also: https://wiki.eclipse.org/PackageDrone/0.14.0/NewAndNoteworthy
