### ISSUE TITLE
Deploy failure through maven

### ISSUE THREAD

**Issue by Sagilisivas2** [ctron/package-drone#152]
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project myapp: Failed to retrieve remote metadata com.maaven.practice:myapp:1.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata com.maaven.practice:myapp:1.0-SNAPSHOT/maven-metadata.xml from/to repoS (http://localhost:8080/nexus-2.14.1-01/content/repositories/repoS/): Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]

**Comment by ctron** [comment]
The project has moved to the Eclipse Foundation: https://github.com/eclipse/packagedrone

However I also don't really get what your actual problem here is: "Connection refused" means that there is no process listen in your port "localhost:8080" ... does a server run on this address and port?
