### ISSUE TITLE
Allow closing a channel

### ISSUE THREAD

**Issue by ctron** [ctron/package-drone#18]
It should be possible to "close" a channel. Which would not allow any more changes to its data or configuration.

The question is: should it still be allowed to change the channel alias? Can a channel be reopened again?

**Comment by toshovski** [comment]
Maybe putting the channel in read only mode would be enough, by deleting the deployment key, or disabling the key.

**Comment by ctron** [comment]
Well in this case the user would still be able to upload an artifact manually.

I think the first step to this is: lock channel, or, as you said: read only.

But this should be a simple flag in the database which prevents all manipulation operations. Including blocking uploads, changing the channel aspects, etc.

But a channel should still be able to get renamed?! So it would be possible to use the alias channel name like a tag or marker.

**Comment by ctron** [comment]
So for now there is a simple "locked" flag for each channel. If the channel is locked, it cannot be modified. But it still can be renamed. However the ID will stay immutable.
