### ISSUE TITLE
I have no channel buttons!

### ISSUE THREAD

**Issue by larkery** [ctron/package-drone#35]
Hello,

This looks like an ideal bit of software for my needs; however, I've just installed it (0.1.2) from the debian package and when I go to the channels page I see no controls for adding a new channel. Am I missing something obvious? I have blindly followed the instructions from the wiki.

Thanks

**Comment by ctron** [comment]
Hi,

It might be that you need to create at least one user and grant him the "manager" role.

The admin account does not have manager rights.

This step might be missing in the wiki.

Jens

**Comment by ctron** [comment]
Added a section in the setup manual.

**Comment by larkery** [comment]
Thanks, that has sorted it out :) 

It might also be worth writing somewhere that the user roles list is a multiselect element, or giving it checkboxes. I did initially guess this as a cause of the problem, but when I looked at the account management page I thought my user already _had_ the role because it was in the list (although now I realize not selected).

**Comment by ctron** [comment]
Yes. You are right! This page has to be improved!
