### ISSUE TITLE
What does the Cleanup function? Can I leave the 10 recent snapshots?

### ISSUE THREAD

**Issue by toshovski** [ctron/package-drone#45]
I have a snapshot p2 repositories. However I need to clean them and leave only the 10 recent snapshots. Also for the release repositories would be a great feature to leave only the recent one. 

I'm not sure how the cleanup works, but it shows, that would delete the most recent artifacts in the channel, but doesn't consider the artifact/groupID. So if I have the following artifacts: a ver 1.0 ,a ver. 1.1,  b ver. 1.0 and b ver. 1.1  and want to delete the recent 1, it would delete: b ver. 1.1 and b ver. 1.0.

What I expect is to delete is the version 1.0 and leave 1.1 for the both artifacts.

**Comment by ctron** [comment]
So basically the cleanup function works like this:

* Aggregate by provided (Aggregator) meta data keys
* Sort by provided (Sorter) meta data keys
* Delete everything before x versions

So when you select the fields [mvn:groupId], [mvn:artifactId], [mvn:version], [mvn:classifier], [mvn:extension] as aggregator fields and [mvn:snapshotVersion] as sorter field. Then for each GAV+C+E package drone will keep the "newest" x entries.

You should be able to use the "test" button to very what will happen. When you press test, the configuration is not saved though!

**Comment by ctron** [comment]
This will be continued in #62
