### ISSUE TITLE
Add an unzip adapter

### ISSUE THREAD

**Issue by ctron** [ctron/package-drone#47]
So in order to use "pre-built" P2 Repositories in ZIP format, we would need an "Unzip Adapter".

The idea is to upload a zipped P2 repository and access it through Package Drone without further processing.

**Comment by ctron** [comment]
So the last commit f4b836d8ce219e7a970de3831581c15b77d58a19, added a basic unzip adapter.

Using the URL: http://myserver/unzip/artifact/`artifact-id`/path/to/file one can access files inside the artifact.

This even works with pre-build P2 repositories.

**Comment by ctron** [comment]
However, I am not sure this helps a lot. Since you actually are not interested in a specific version of the P2 repository (addressed by the artifact ID), but by "the most recent one of channel X".

**Comment by toshovski** [comment]
Well for the p2 repository I'm interested by all versions, not the most recent one.

**Comment by ctron** [comment]
So a stable URL with the artifact ID would be OK?

**Comment by toshovski** [comment]
yes. Do you unzip them and add them to the repository, or the whole repository is handled as a bundle?

**Comment by ctron** [comment]
The whole repository zip file is an artifact. The unzip adapter just allows to access files inside an artifact which is a zip file.

I need this for other things as well. For example viewing the about.html inside a bundle or feature.

I would also like to have a channel aspect which creates virtual artifacts based on the repository zip content. But if the unzip adapter is OK for you, bi would just skip that for the moment.

**Comment by toshovski** [comment]
If I upload multiple versions of the p2 repository bundle... Would I see all of them using the http://myserver/unzip/artifactID/ or only the latest one?

**Comment by ctron** [comment]
Ok, that is why I meant. You would only see the one your are directly referencing to. Based on the "artifact id". So after uploading you would need to locate the artifact, note the ID and use the ID afterwards in the URL.

And I am not sure if this is practical.

So I would guess that one would need some more like: "the latest artifact with name 'x'" instead of 'by id'.

**Comment by ctron** [comment]
Ok, so the version which supports "by artifact id", "newest by name" and "newest" is in version 0.2.2

**Comment by ctron** [comment]
I did add a little bit of documentation here: https://github.com/ctron/package-drone/wiki/Unzip-Adapter

**Comment by cbrun** [comment]
Hi, just giving my input and I hope I'm not hi-jacking this issue.
The unzip-adapter sounds very useful to us at first sight, here is our use case

ProjectA builds an update-site - projectA.zip and publish it on package drone
ProjectB consume this update-site, and is interested in consuming the "latest which got published", hence need a stable URL for this latest update-site content.

So far in my testings with Package Drone 0.2.4.20150305
- ProjectA using mvn deploy, the update-site gets published on package-drone but a build qualifier is added in the zip name => ProjectB can't use " latest artifact with name 'x'". And it seems I have no control on this qualifier being added, I'm using Tycho with a specific configuration to not have this qualifier in the zip name
           <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-p2-repository-plugin</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <createArtifactRepository>true</createArtifactRepository>
                    <finalName>${project.artifactId}</finalName>
                    <compress>true</compress>
                </configuration>

newestByArtifactID could work for us if the artifact ID is not the "Package Drone Artifact ID" but the Maven one 

To take a step back in our case, ProjectB is actually interested in "getting the lastest stable build of ProjectA/1.2.0" or "getting the latest nightly build of ProjectA/1.2.x" or "getting the latest released build of ProjectA/x.x.x/  which makes it sounds more like a general URI rewriting mechanism.

**Comment by ctron** [comment]
This is valid and important input! That's why I kept the issue open. Since I knew there are will be several use cases where the current feature set is not enough. It we find additional bugs or enhancements, we can open and reference new bugs for these. But would like to keep the discussion here.

Unfortunately I have to leave the office now and will read it in detail later this evening or tomorrow.

But thanks for the input!!

**Comment by cbrun** [comment]
Thanks !
Again, take my comment with a grain of salt as we just started experimenting with PackageDrone and not quite sure yet how we would use it. In itself, our use of zipped update-sites is mainly a way to have a single and consistent output for "a given build" which I guess is something PackageDrone could be able to provide at the "Channel" level or through virtual artifacts in a more generic way.

If we could have some URIs for p2 repositories in the form of 
http://host/p2/CBBA1950-C7A8-4275-81B9-EFADBF80BCE8/1.0.1/20150305.152643-1 
http://host/p2/CBBA1950-C7A8-4275-81B9-EFADBF80BCE8/1.0.x/ (latest minor update)
http://host/p2/CBBA1950-C7A8-4275-81B9-EFADBF80BCE8/1.x.x/ 

we might not even need the Unzip adapter.

**Comment by ctron** [comment]
Ok, I start to see what you do.

So, are we talking about release or integration/snapshot builds? Maven has the Snapshot concept, however some people don't use it in combination with Tycho.

In theory there could be two channels. One release and one snapshot. This would also work with maven since it has different deployment settings for release and snapshot.

I will try to think about the version idea. It like the idea of 1.x.y as a reference. We can create categories which could solve this. But there could also be the channel alias/name, which simply can be passed on to the next channel.

**Comment by ctron** [comment]
Ok, I did a brainstorming session this morning with my colleague. I tried to write down the result in some sort of document on Google Docs [1].

I would like to use this document to find out what you need. The more I think about it, the more I think we can use the same process for hosting Eclipse SCADA and openSCADA. So I would really be interested in moving this forward.

If this is ok for you, I would like to share the document with you, so that you can comment or edit it. But I guess I need your gmail address for this, which I would understand if you don't hand it out.

[1] https://docs.google.com/document/d/1Vkifasrfy_aWZ7bckFTFRiglSG2hgwXertvHon51cV4

**Comment by ctron** [comment]
Ok, so I did start with an implementation of the Unzip part, which is documented over here [1] and is contained in the latest RC release (0.3.0.rc2). 

This release is however an RC release and there not available in docker. But I made an OpenShift branch ("next"), see [2] for more information on how to use the "next" branch.

This should allow the most cases like direct referencing a release, or snapshot or target something like 1.2.x and 1.x. At least for an uploaded P2 ZIP.

I would kindly ask you to give it a try.

[1] http://doc.packagedrone.org/book/unzip_adapter.xhtml#ra_unzip_maven
[2] https://github.com/ctron/package-drone-openshift#using-next

**Comment by toshovski** [comment]
"However this version is not available when manually uploading the artifact!" --> The version is avaliable. You can set the version of the artifact, when you upload the artifact [1]

Your idea with equivalent, compatible and latest is really good. The main problem of p2 is the usage of target platforms, because it requires exact version. So we will still need to use the targetplatform plugin, which has the same functionality, like you provide.

This might be a new level for repository management, if there is a way to merge and composite them (virtually).

[1] http://maven.apache.org/guides/mini/guide-3rd-party-jars-remote.html

**Comment by ctron** [comment]
Ok, you are right. What I meant was "manually uploaded using the Web UI", manually using maven it is. Thanks.

That is why I really would like to generate the target platform file for the channel. And maybe even the maven project around that. One step at a time :wink:

**Comment by ctron** [comment]
Ok, so this first feature set for the unzip adapter is now in Package Drone 0.3.0 and also available in the default OpenShift setup.

**Comment by toshovski** [comment]
Generating the target platform is nice, but how would you bind it with tycho?

**Comment by ctron** [comment]
Well with tycho you can reference a target platform inside as a maven artifact. But we should continue this discussion over at #46 :wink:

**Comment by ctron** [comment]
So I am closing this issue for now, since there is an unzip adapter in place.
