### ISSUE TITLE
0.4.0 - cannot send mails

### ISSUE THREAD

**Issue by maggu2810** [ctron/package-drone#51]
Hello, cannot send mail using a newly installed release.
I never used this software before. I found it and would like to test it.
I configured the mail account settings and tried to send a test mail. The browser still waiting for data from localhost (package-drone server).

**Comment by maggu2810** [comment]
Okay, sorry, some misconfiguration first.
But still have some problems.
What connection settings are you using:
<pre>530 5.7.0 Must issue a STARTTLS command first. hl15sm6019492wib.3 - gsmtp</pre>

**Comment by ctron** [comment]
Hi,

are you using the OpenShift image?

Did you try the default mail settings (when using OpenShift)?

Which mail provider did you enter?

The system uses Java Mail, with SMTP as transport. If you enter a username and password it will also use this authenticate the SMTP connection. However there is no support for TLS right now. Since the basic idea is to use a machine local mail server.

**Comment by ctron** [comment]
So maybe we would need a simple "TLS" option which triggers:
```
mail.smtp.starttls.enable=true
```
In the Java Mail session creation.

**Comment by maggu2810** [comment]
I want to have a look at the software to decide if I will start using this on a server.
So I want to use my private gmail account.

**Comment by ctron** [comment]
Well I am not sure if gmail allows you to use their server for relaying. Which is what you would need for that.

The best thing is to use the default settings on openshift, use a local mail server like Postfix or a mail service like mailgun.

**Comment by ctron** [comment]
So do you use the openshift setup?

**Comment by maggu2810** [comment]
I followed the manual install guide on the wiki page and using the zip file of the release page.
https://github.com/ctron/package-drone/releases/download/v0.4.0/package-drone-server-0.4.0.zip

**Comment by ctron** [comment]
OK, so the easiest way to try it out is the openshift setup.

In your case you simply need to install a local mail server, like postfix. And use this with "localhost" and no username/password. Most Linux distributions allow relaying email using this setup.

If you don't plan to send emails, do just testing for yourself, you can also ignore the email setup.

**Comment by ctron** [comment]
So the next version (0.4.1) will allow enabling STARTTLS.

**Comment by maggu2810** [comment]
Great, thank you.
