### ISSUE TITLE
set package drone specific user agent header

### ISSUE THREAD

**Issue by CptMauli** [ctron/package-drone#55]
So next time it will hopefully appear in the blog post of the sonatype guys ;-)

http://blog.sonatype.com/2014/11/42000-nexus-repository-managers-and-growing/#.VQky38u1LRY

**Comment by ctron** [comment]
This would need to be set for the Aether library which is used by package drone to fetch things from maven repositories.

**Comment by ctron** [comment]
User Agent reported as `User-Agent: PackageDrone/0.4.1 (+htp://packagedrone.org)`

**Comment by ctron** [comment]
Fix to "http" instead of "htp"
