### ISSUE TITLE
Support maven deployment from the gradle maven-publish plugin

### ISSUE THREAD

**Issue by larkery** [ctron/package-drone#61]
Hello,

Having become unable to cope with writing any more POM files I've been building some of my bundles with gradle instead, which is all much nicer except that it doesn't produce quite the same `maven-metadata.xml` as maven itself does when deploying. Rather than having `snapshotVersions` and so on it just has `versioning/versions/version` in the outer metadata file and `versioning/snapshot` in the inner one.

I think this is because behind the scenes it's using some slightly older code from maven to do the deploy, which doesn't support the newer metadata. At the moment I can just get gradle to invoke the maven deploy task, but I would like to fix it properly.

Anyway, I'm happy to try and fix this either by fixing gradle (looks potentially quite complicated), or by persuading package-drone to handle the older `maven-metadata.xml` (looks easier). However, before I start I thought I'd ask whether you'd be likely to accept a pull request for this?

Thanks,

tom

**Comment by ctron** [comment]
Hi,

I would be happy to accept a pull request for this. I have to admit that I never used gradle until now.

If you need any help, please let me know! The upload code in the MavenServlet is a bit weird I would say. Although it is not really complex. The way maven uploads files (and the order) is a bit strange as well. So if you like to refactor, just go ahead!

Thanks for helping!

**Comment by larkery** [comment]
OK, I will take a crack at it and see how I get on. I also find maven's approach pretty weird, and kind of stupid (what if two people deploy something at once? there is an awful race condition), but there we go.

I have another thing I might take a look at which is about redeploying existing artifacts; at the moment if I upload something again with the same version I get an error 500. It might be nice to be able to allow replacing the existing version, although this is obviously dodgy if you want genuine repeatability of builds.

**Comment by ctron** [comment]
Yes I agree!

The re-deployment topic is covered a bit in #56 

Right now there is no clear policy except that Package Drone itself does not care.

The right choice would be to assign a policy (fail, ignore, replace) and return an appropriate HTTP error code.

**Comment by ctron** [comment]
I just tried to read a little bit about deployments with gradle, however there seem to be multiple ways to do it. Do you have an example?

**Comment by larkery** [comment]
I think the supported way for current and future versions is using 'publications', for which the build file should look like:

```groovy
apply plugin: 'java'
apply plugin: 'maven-publish'

version = '1.0.0'
group = 'org.example.thing'

publishing {
   publications {
      mavenJava(MavenPublication) { from components.java }
   }
   repositories { maven { url "http://url-of-your-repo" } }
}
```

so if you have that in `build.gradle` in a folder called `project` and then you run `gradle publish` it should make a nearly empty jar file, and upload it to the repo as `org.example.thing:project:1.0.0`. This depends on having a fairly new gradle, so if you have installed it through apt on debian you might need to get gradle to update itself. There is a special gradle task you can put in which does this, if you add

```groovy
task wrapper(type: Wrapper) {
    gradleVersion = '2.4' // this is the latest; my ticket was raised using 2.3, so I will have a go and see if 2.4 works
}
```

then you can run `gradle wrapper` and it will bootstrap itself to a newer gradle and stick a script in the project directory called `gradlew`; then you can run that as `./gradlew publish` or whatever and it will run the downloaded version instead.

I haven't had time to look at this properly yet myself and have instead resorted to using non-snapshot versions with a timestamp qualifier on them instead, which seems to do the job (particularly since OSGi has no interest in snapshots anyway, and that is what I am really using the repository for).

**Comment by ctron** [comment]
I just tried your project using a fresh download of Gradle 2.4 on Linux with Package Drone 0.8.1:

* Created a new channel `gradle1`
* Assigned deploy keys

```Gradle
apply plugin: 'java'
apply plugin: 'maven-publish'

version = '1.0.0'
group = 'de.dentrassi.pm'

publishing {
   publications {
      mavenJava(MavenPublication) { from components.java }
   }
    repositories { 
        maven {
            credentials {
                username 'deploy'
                password 'xxxxxxxx'
            }
            url "http://localhost:8080/maven/gradle1"
        }
    }
}
```

Run: `gradle publish`

```ShellSession
jens@zeropoint ~/Development/workspace_opm/pkgrepo/test.gradle1 $ gradle publish
:generatePomFileForMavenJavaPublication
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:publishMavenJavaPublicationToMavenRepository
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/1.0.0/test.gradle1-1.0.0.jar
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/1.0.0/test.gradle1-1.0.0.jar.md5
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/1.0.0/test.gradle1-1.0.0.jar.sha1
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/1.0.0/test.gradle1-1.0.0.pom
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/1.0.0/test.gradle1-1.0.0.pom.md5
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/1.0.0/test.gradle1-1.0.0.pom.sha1
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/maven-metadata.xml
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/maven-metadata.xml.md5
Upload http://localhost:8080/maven/gradle1/de/dentrassi/pm/test.gradle1/maven-metadata.xml.sha1
:publish

BUILD SUCCESSFUL

Total time: 2.935 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
```

So this looks good to me.

![pd_gradle_1](https://cloud.githubusercontent.com/assets/202474/7683526/02929d50-fd80-11e4-9e0b-273a1f4fae50.png)

**Comment by ctron** [comment]
I did several deployments now with gradle and they seem to work fine.

**Comment by larkery** [comment]
I am still having some troubles. The issue appears when I deploy artifacts with a -SNAPSHOT version; whole numbered versions don't appear to cause a problem. I have been happily working around this by endlessly bumping version numbers :)

**Comment by ctron** [comment]
OK, I will give it a try in about two weeks. Currently I am on vacation ;-)

**Comment by larkery** [comment]
OK - enjoy; as far as I can tell the sequence is like this: `processUpload` -> `storeTmp` successfully saves the jar into a temp location, but then the metadata uploaded afterwards is not handled successfully by `processMetadata` and so the artifact is not attached to the database in any way. Upload appears successful but has no side-effects on the repository. This kind of thing appears in the log output:

 ```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<metadata>
  <groupId>uk.org.cse.nhm</groupId>
  <artifactId>bundle-impl</artifactId>
  <version>6.2.0-SNAPSHOT</version>
  <versioning>
    <snapshot>
      <timestamp>20150812.163518</timestamp>
      <buildNumber>1</buildNumber>
    </snapshot>
    <lastUpdated>20150812163518</lastUpdated>
  </versioning>
</metadata>
```

After which nothing happens. I think the log output is from [this line](https://github.com/ctron/package-drone/blob/b21581ff45f0392cdeee7e2334f494ceacec5923/de.dentrassi.pm.maven/src/de/dentrassi/pm/maven/internal/MavenServlet.java#L420).

Reading the code further, it looks like [this loop](https://github.com/ctron/package-drone/blob/b21581ff45f0392cdeee7e2334f494ceacec5923/de.dentrassi.pm.maven/src/de/dentrassi/pm/maven/internal/MavenServlet.java#L456) won't get hit as there is no `versioning/snapshotVersions/snapshotVersion` element in the `metadata`. I'm not entirely sure why this is not supplied, and have been digging about to see whether I am missing something on the gradle side, but no luck so far.

**Comment by ctron** [comment]
I just played a little bit around with gradle, doing snapshot builds. Gradle actually makes the maven upload process even worse. Adding a source attachments again changes the flow of upload to: `jar -> pom -> artifact metadata -> version metadata -> sources`.

So in your patch, the sources would get ignored as well.

I guess the maven upload process needs a bit more intelligence to handle maven and gradle, release and snapshot, and the (still missing) checksum validation at the same time.
