### ISSUE TITLE
maven: consuming artifacts

### ISSUE THREAD

**Issue by maggu2810** [ctron/package-drone#71]
Is the consuming of artifacts using maven (or to look around a browser on the url <host>/maven/<channes>) only possible if the artifacts were uploaded using maven deploy?
I created a channel and upload bundles using the drop feature of the web page. This channel shows no content using the specific maven url. Exist this problem because of the missing xyz.pom file? This pom files are included in the jar (normally). Could we extract them?

**Comment by ctron** [comment]
Yes, this is true. Right now the Maven repository only works if the files got uploaded by maven *and* the maven repository aspect is present.

True, the pom file could be extracted from the JAR and the "groupId", "artifactId" and "version" could be extracted from the pom file as well.

**Comment by ctron** [comment]
So the only thing that would be needed from quick look at it, might be a virtualizer which extracts the POM file from the JAR. And a meta data extractor which extracts the GAV information from the POM. The rest should be automatic based on what is already there.

**Comment by ctron** [comment]
So extracing the pom and the metadata for the pom was easy.

The hard part is getting the maven meta data one layer upwards to the jar file.

**Comment by maggu2810** [comment]
If that is hard for you, it would be much harder for someone that does not know the architecture. ;-)
Thank you, I think this would be a great feature!

**Comment by ctron** [comment]
True :wink:  But I will keep working on this. And if you are in Munich, I can explain it to you while having some :beer:

**Comment by ctron** [comment]
Ok, so the last commit does locate the child pom artifact and take GAV from it, using the extension from the local artifact name.

In the end this creates a Maven Repository entry for the artifact based on the extracted POM file.

So for this to work, two aspects have to be present on the channel: Maven Extractor, Maven Repository

**Comment by ctron** [comment]
And I just incremented the Maven Repository aspect version to indicate a change in the meta data format.

**Comment by maggu2810** [comment]
Great!

**Comment by ctron** [comment]
Do you have way to test it without a milestone build?

**Comment by maggu2810** [comment]
I will use the Eclipse IDE with the master branch.

**Comment by maggu2810** [comment]
I use the drag and drop feature of the newly created channel (with all aspects added) and dropped two jar files (karaf console bundles, but that should not be related).

I configured maven to use the local test package-drone channel as mirror of *.

I started the following commands to download the two jar and the two pom files using maven.

<pre>
mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:copy -Dartifact=org.apache.karaf.shell:org.apache.karaf.shell.core:4.0.0.M2:jar -DoutputDirectory=.
mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:copy -Dartifact=org.apache.karaf.shell:org.apache.karaf.shell.core:4.0.0.M2:pom -DoutputDirectory=.
mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:copy -Dartifact=org.apache.karaf.shell:org.apache.karaf.shell.console:4.0.0.M2:jar -DoutputDirectory=.
mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:copy -Dartifact=org.apache.karaf.shell:org.apache.karaf.shell.console:4.0.0.M2:pom -DoutputDirectory=.
</pre>

cut down output:
<pre>
Downloading: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.console/4.0.0.M2/org.apache.karaf.shell.console-4.0.0.M2.jar
Downloaded: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.console/4.0.0.M2/org.apache.karaf.shell.console-4.0.0.M2.jar (351 KB at 760.9 KB/sec)

Downloading: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.console/4.0.0.M2/org.apache.karaf.shell.console-4.0.0.M2.pom
Downloaded: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.console/4.0.0.M2/org.apache.karaf.shell.console-4.0.0.M2.pom (9 KB at 31.4 KB/sec)

Downloading: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.core/4.0.0.M2/org.apache.karaf.shell.core-4.0.0.M2.jar
Downloaded: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.core/4.0.0.M2/org.apache.karaf.shell.core-4.0.0.M2.jar (371 KB at 1142.4 KB/sec)

Downloading: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.core/4.0.0.M2/org.apache.karaf.shell.core-4.0.0.M2.pom
Downloaded: http://127.0.0.1:8082/maven/13B1E385-5484-4FF0-A4ED-B12376117653/org/apache/karaf/shell/org.apache.karaf.shell.core/4.0.0.M2/org.apache.karaf.shell.core-4.0.0.M2.pom (8 KB at 25.8 KB/sec)
</pre>

Fine!

**Comment by maggu2810** [comment]
I think we could close the issue. Ok?

**Comment by maggu2810** [comment]
The unzipped pom files are all named pom.xml.
Should we rename that files to use the name of the jar file and just replace the ending .jar with .pom?
That would be the result if we use maven deploy.

**Comment by ctron** [comment]
Cool :) Thanks for testing.

Well I did consider this as well. The name. However right now the parent artifact needs to find group, artifact, version from the child artifact. And the child artifact is currently found by simply looking for `pom.xml`. And in the directory index it also is called `artifact-id.pom`.

Of course the parent could also look for `basename.pom` ... I am not sure ...

**Comment by maggu2810** [comment]
It would be much nicer for the channel view "List" (url: .../viewPlain), as this shows a lot of "pom.xml" files.
Sure, the "Content" view will group this, but it would be nice, if the name (in the list view) would be equal to that one maven deploy is using.

**Comment by ctron** [comment]
True! The list view will look horrible that way. I am rarely using it anymore ;-)

Ok ... I will change it!

**Comment by ctron** [comment]
Done :white_check_mark:

**Comment by ctron** [comment]
You will need to regenerate the metadata in order to see it. Both ways are possible now.

**Comment by maggu2810** [comment]
This is very great!

**Comment by ctron** [comment]
Cool, thanks!
