### ISSUE TITLE
MD5 hash is not as expected (source bundles)

### ISSUE THREAD

**Issue by maggu2810** [ctron/package-drone#73]
If I want to use a p2 repository in the Eclipse IDE (setup a target platform) that contains also source bundles, I get MD5 mismatches.
* All aspects are activated in the channel.
* Artifacts have been deployed using maven.
* A feature using the feature generator was added.

I added the generated feature of the p2 repo to a eclipse target definition.

<pre>
Problems downloading artifact: osgi.bundle,here.is.the.bundle.name.source,0.8.0.201504141550.
  MD5 hash is not as expected. Expected: ... and found ....
</pre>

**Comment by ctron** [comment]
Hi,

This can happen if there is a artifact listed twice (by bundle name and version) which in fact is different.

P2 has no way of distinguishing between two artifacts which have the same name and version.

**Comment by maggu2810** [comment]
Should package-drone detect that mismatch and inform the user on the p2 information page (http://127.0.0.1:8080/p2.repo/.../info) about that problem.
So we could see the artifacts duplicates and remove one of them.

**Comment by ctron** [comment]
I totally agree that there should be some P2 validation. See issue #20.

So during the P2 aggregation run the system could check if there are duplicates and then warn about these.

With P2 the topic of locating an artifact should be simple and configurable, but actually is quite strict and limited. For each classifier (bundle, binary, feature) there is a "rule" (e.g. for "bundle" -> "${repoUrl}/plugins/${id}_${version}.jar"). However this rule is valid for ALL artifacts in the channel. And the only variables which can be used are "repoUrl", "id" and "version". So there is no way to distinguish between two bundles with the same id and version.

I did have this problem with an Eclipse source bundle, which also was a maven source artifact. This created two artifacts (the plain jar and the virtualized source bundle). Which both had the same id and the same version, but actually different content.

So in the end, there should be some form of validation. Which sums up the state of the channel and provides validation warnings and errors. Any possibly a policy what happens in the case of validation errors.

But this whole idea still is an idea and not source code :wink:

**Comment by ctron** [comment]
Commit f4c6de2b70a876b285f8768270f5363dd71dbb18 brings in the required functionality to identify this situation and at least provide a validation error message.

Still there is no solution to this, just raising awareness of the user.
