### ISSUE TITLE
Double Slash in URL not valid

### ISSUE THREAD

**Issue by cornzy** [ctron/package-drone#75]
When I have a URL that (maybe out of mistake) have a double slash, the result should be the same as without double slash. e.g.

https://example-drone.com/unzip/maven/prefixed//channel-id/groupId/artifactId/version/...

After "prefixed" I had two slashes. Result: Channel with ID or name '' not found

**Comment by ctron** [comment]
This is a clear bug. I try to fix it in the next version. If nobody else is first ;-)

**Comment by ctron** [comment]
Provided a fix in 0.7.3
