### ISSUE TITLE
Storage service not present after upgrade

### ISSUE THREAD

**Issue by larkery** [ctron/package-drone#76]
Hello,
I just upgraded to a newer version of the debian package, and it went back to the "install wizard"; I have logged in with the admin token again, put in DB details and upgraded the schema, but it seems to fail to let me pass the database setup phase. The diagnostic box in the page says:

Thing | Other Thing
--------|---------
Database schema version	| 12
Current schema version | 	12
Storage service present	| false

But doing a connection test etc. works. Pressing submit seems to take a long time, whatever that is doing.
The end of the log is:
```
!MESSAGE Could not bind a reference of component de.dentrassi.pm.mail.web.task. The reference is: Reference[name = MailService, interface = de.dentrassi.pm.mail.service.MailService, policy = dynamic, cardinality = 0..1, target = null, bind = setService, unbind = unsetService]

!ENTRY org.eclipse.equinox.ds 1 0 2015-04-28 18:16:38.675
!MESSAGE Could not bind a reference of component de.dentrassi.pm.storage.web.setup. The reference is: Reference[name = StorageService, interface = de.dentrassi.pm.storage.service.StorageService, policy = dynamic, cardinality = 0..1, target = null, bind = setService, unbind = unsetService]
```
I can set it up again from scratch, but would prefer not to.
Any thoughts?

**Comment by ctron** [comment]
I have seen this as well. It seemed as if the configuration admin does not push the configuration to the service.

I was able to "fix" it by starting the "server" script with the argument "-clean" and re-entering the database configuration.

**Comment by larkery** [comment]
Will see if that fixes it and get back to you (tomorrow, going home now)

**Comment by larkery** [comment]
that seems to have worked, thank you
