### ISSUE TITLE
Deployment with maven-deploy-plugin is not working anymore

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#85]
With the new version 0.8.0 the deployment with maven-deploy-plugin is not working anymore. The plugin tries to download a file .../maven-metadata.xml, which fails for a channel without the aspect "maven repository" (error 503).
If I add this aspect to the channel, the deployment with the maven-plugin works again, but now I get errors on multiple deployments for the same artifact (error 500).
The console log shows the following errors in the exception stacktrace:
Failed to run channel aggregator: maven.repo
...
Invalid hierarchy. <artifact>.pom is already used. (here is a concrete artifact named)

Please reenable the deployment to package-drone with maven-deploy-plugin (or name another plugin) without the aspect "Maven Repository". Or suppress the error for redeployment of artifacts.

**Comment by ctron** [comment]
This is strange. Because there should be no change in this area. And once the "Maven Repo" aspect is added there really is a limitation that duplicate artifacts (with the same version) cannot be uploaded. However this should be possible to upload without the Maven Repository aspect, so this restriction does not get applied.

From which version did you upgrade?

**Comment by afischer211** [comment]
I used the version 0.7.3 before and upgrade to 0.8.0 yesterday. Now I get the named errors on deployment with maven-deploy-plugin. With version 0.7.3 this problem does not occur.
If I try to access the URL for the file "http://<pdrone-server>/maven/<channel-alias>/<path=groupId>/<artifactId>/maven-metadata.xml" within browser, I get a page with the short message "Corrupt channel data". I think, the maven-deploy-plugin tries to detect over this file, if the artifact should be deployed to the repository.
May be I should write a new Maven-plugin (Mojo) for deployment over the new Web-API?

**Comment by ctron** [comment]
No writing a custom Mojo to solve this issue is not the solution, although such a mojo would be quite nice :wink: 

Is there an open task (upper right edge) which requests you to regenerate the meta data?

**Comment by afischer211** [comment]
There was open tasks after the update and I runs all.
I have also (after some failed retries) started pdrone with parameter -clean and reentered all configuration-datas. Only the scheme on the MySQL-database I have not dropped. Also a complete clear of the channel (with the button on the web-gui) does not help.
The database-scheme has the version 13 (after updating). May be the update for the database-scheme has some trouble? How can I debug into the problem?

**Comment by ctron** [comment]
Do you have an easy, reproducible maven project which I can use to reproduce this issue?

**Comment by afischer211** [comment]
Ok, I have prepared a simple project. It builds an empty eclipse-feature and if you call mvn deploy with the parameter **`-DaltDeploymentRepository`**, you run into the error.
I think, every project with building feature or bundle is influenced by the bug.
How can I provide the zip-archive? Or should I insert the 3 files (build.properties, pom,xml and feature.xml) directly in the comment?

**Comment by afischer211** [comment]
**pom.xml:**

`<?xml version="1.0" encoding="UTF-8"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<modelVersion>4.0.0</modelVersion>

	<groupId>test</groupId>
	<artifactId>test.feature</artifactId>
	<version>0.0.1</version>
	<packaging>eclipse-feature</packaging>

	<build>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>0.21.0</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-packaging-plugin</artifactId>
				<version>0.21.0</version>
			</plugin>
		</plugins>
	</build>
</project>`

**feature.xml:**

`<?xml version="1.0" encoding="UTF-8"?>
<feature
      id="test.feature"
      label="test bundles"
      version="0.0.1"
      provider-name="xxx">

</feature>`

**build.properties:**

`bin.includes = feature.xml
javacDefaultEncoding.. = Cp1252`

**Comment by ctron** [comment]
Ok, I will give it a try!

**Comment by ctron** [comment]
If I do deploy in a channel without the "Maven Repository" aspect, then it fails. If the aspect was added it works.

This really was different in the past.

**Comment by ctron** [comment]
So this really was bug introduced after the 0.7.3 release. Sorry for that, and thanks for helping!

The actual problem was that the API did specify that, in case of an unknown cache entry, a FileNotFoundException is being thrown. However this one was wrapped in a RuntimeException, so it was never caught.

A FileNotFoundException however would have triggered a 404, which indicates to Maven, that the file is not existing and will be created anew. In the case of a RuntimeException a 503 would be returned, indicating that the repository is corrupted.

**Comment by ctron** [comment]
I will make a release 0.8.1 right now and let you know when it got uploaded.

**Comment by ctron** [comment]
The release should be available.

**Comment by afischer211** [comment]
The bug is solved with release 0.8.1
