### ISSUE TITLE
"Content-Disposition" header missing when downloading artifact from artifacts view

### ISSUE THREAD

**Issue by SvenEwald** [ctron/package-drone#90]
Minor issue in the details page for artifacts:
- Go to channel contents
- Click on details for a jar
- Click on download
- Instead of downloading the jar, a download of "dump" is startet.

It works in the channel contents page, but not in the artifact details page.
PD 0.9.0, FF 38.0.1

**Comment by ctron** [comment]
Damn! Thanks for reporting!

**Comment by afischer211** [comment]
I can commit the bug. But the content of the downloaded "dump"-file is ok (only the bad name-suggestion).

**Comment by ctron** [comment]
Ok, so I guess the artifact is downloaded without a proper `Content-Disposition` header in the HTTP response header.

**Comment by ctron** [comment]
The link labeled "download" actually pointed to the "view" action of the artifact. So clicking on a binary artifact, which the browser does not understand, or the mime aspect is missing, then the browser suggests to save the artifact as `dump`.

The download link was redirected to the "get" operation, which provides the `Content-Disposition` header with the correct filename. Also the "view" button was added. So both, channel and artifact view, now provide the same operations.
