### ISSUE TITLE
Upload bundles via upload API does not give bundle classifier

### ISSUE THREAD

**Issue by SvenEwald** [ctron/package-drone#91]
PD v0.9.0
Using`curl -X PUT --data $file $url` adds the bundle without classifier in the channel.
Afterwards, bundle is not in the p2 metadata.

But:
Manually dropping the same bundle on "drop Artifacts" works. Bundle is shown in content list with "OSGI Bundle" classifier and shows in p2 metadata.

**Comment by SvenEwald** [comment]
Example in screenshot: The first 11 bundles have been uploaded via the upload API,
the next 2 manually via drag & drop:
![2015-05-22 10_44_10-channel _ package drone](https://cloud.githubusercontent.com/assets/3087815/7767077/d0500a92-006f-11e5-9fe2-78d5f0630ccc.png)

**Comment by afischer211** [comment]
Did you try to activate the aspect "P2 Metadata Generator"? May be the download over drag&drop calls the metadata generator automatically?

**Comment by ctron** [comment]
It seems strange to me that the uploaded artifacts are actually pretty small. Did the upload really work?

**Comment by SvenEwald** [comment]
Good observation, I'll check whether the upload was successful. Regarding the size, it seams to be broken.

**Comment by SvenEwald** [comment]
Found the problem: Subtile error in the upload script (my side). Used `curl -X PUT --data file` instead of `curl -X PUT --data @file`.  `-T file` works, too.

**Comment by ctron** [comment]
Ok :-) so I can close this issue?
