### ISSUE TITLE
Missing column in table properties (schema version 14)

### ISSUE THREAD

**Issue by SvenEwald** [ctron/package-drone#92]
found some stacktraces in the console:
>Caused by: java.lang.RuntimeException: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Service                                                                                                         s - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DatabaseException
>Internal Exception: org.postgresql.util.PSQLException: FEHLER: Spalte â€žnsâ€œ existiert nicht
>  Position: 8
>Error Code: 0
>Call: SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN (?,?))
>        bind => [3 parameters bound]
>Query: ReportQuery(referenceClass=GlobalPropertyEntity sql="SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN ?)")
>        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:113) ~[de.dentrassi.pm.common_1.0.                                                                                                         0.20150518-0856.jar:na]
>        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl$$Lambda$25/975802242.process(Unknown Source) ~[na:na]
>        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithManager(AbstractJpaServiceImpl.java:48) ~[de.dentrassi.pm.common_                                                                                                         1.0.0.20150518-0856.jar:na]
>        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:68) ~[de.dentrassi.pm.com                                                                                                         mon_1.0.0.20150518-0856.jar:na]
>        ... 46 common frames omitted
>Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070)                                                                                                         : org.eclipse.persistence.exceptions.DatabaseException
>Internal Exception: org.postgresql.util.PSQLException: FEHLER: Spalte â€žnsâ€œ existiert nicht
>  Position: 8
>Error Code: 0
>Call: SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN (?,?))
>        bind => [3 parameters bound]
>Query: ReportQuery(referenceClass=GlobalPropertyEntity sql="SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN ?)")
>        at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:382) ~[na:na]
>        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:260) ~[na:na]
>        at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473) ~[na:na]
>        at de.dentrassi.pm.core.jpa.CoreServiceImpl.lambda$2(CoreServiceImpl.java:76) ~[na:na]
>        at de.dentrassi.pm.core.jpa.CoreServiceImpl$$Lambda$28/1720158628.processVoid(Unknown Source) ~[na:na]
>        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$0(AbstractJpaServiceImpl.java:59) ~[de.dentrassi.pm.common_1.0.0                                                                                                         .20150518-0856.jar:na]
>        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl$$Lambda$24/1121013202.process(Unknown Source) ~[na:na]
>        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:80) ~[de.dentrassi.pm.common_1.0.0                                                                                                         .20150518-0856.jar:na]
>        ... 49 common frames omitted
>Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
>Internal Exception: org.postgresql.util.PSQLException: FEHLER: Spalte â€žnsâ€œ existiert nicht
>  Position: 8
>Error Code: 0
>Call: SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN (?,?))
>        bind => [3 parameters bound]
>Query: ReportQuery(referenceClass=GlobalPropertyEntity sql="SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN ?)")
>        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340) ~[na:na]
>        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:684) ~[na:na]
>        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560) ~[na:na]
>        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2055) ~[na:na]
>        at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570) ~[na:na]
>        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[na                                                                                                         :na]
>        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[na                                                                                                         :na]
>        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299                                                                                                         ) ~[na:na]
>        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694) ~[                                                                                                         na:na]
>        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2740)                                                                                                          ~[na:na]
>        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllReportQueryRows(ExpressionQueryMechanism.java:2677                                                                                                         ) ~[na:na]
>        at org.eclipse.persistence.queries.ReportQuery.executeDatabaseQuery(ReportQuery.java:852) ~[na:na]
>        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904) ~[na:na]
>        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1132) ~[na:na]
>        at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:442) ~[na:na]
>        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1220) ~[na:na]
>        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[na:na]
>        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857) ~[na:na]
>        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839) ~[na:na]
>        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804) ~[na:na]
>        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258) ~[na:na]
>        ... 55 common frames omitted
>Caused by: org.postgresql.util.PSQLException: FEHLER: Spalte â€žnsâ€œ existiert nicht
>  Position: 8
>        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270) ~[na:na]
>        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998) ~[na:na]
>        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[na:na]
>        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570) ~[na:na]
>        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420) ~[na:na]
>        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:305) ~[na:na]
>        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1009) ~[na:na]
>        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:644) ~[na:na]
>        ... 74 common frames omitted
>[EL Warning]: 2015-05-22 09:59:19.791--UnitOfWork(72967016)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.v2015030                                                                                                         9-bf26070): org.eclipse.persistence.exceptions.DatabaseException
>Internal Exception: org.postgresql.util.PSQLException: FEHLER: Spalte â€žnsâ€œ existiert nicht
>  Position: 8
>Error Code: 0
>Call: SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN (?,?,?))
>        bind => [4 parameters bound]
>Query: ReportQuery(referenceClass=GlobalPropertyEntity sql="SELECT NS, "KEY", "VALUE" FROM PROPERTIES WHERE (NS || ? || "KEY" IN ?)")
>[EL Info]: 2015-05-22 10:16:20.756--ServerSession(114412555)--EclipseLink, version: Eclipse Persistence Services - 2.6.0.v20150309-bf260                                                                                                         70
>[EL Info]: connection: 2015-05-22 10:16:20.792--ServerSession(114412555)--/de.dentrassi.osgi.job.jpa_nonJtaDataSource=755553112 login su                                                                                                         ccessful
>
>

**Comment by ctron** [comment]
Did you upgrade or install a new instance? In the case of an upgrade this is OK since the table holding the database schema information changed.

**Comment by SvenEwald** [comment]
it was an update frim 0.8.0. Did not notice any further harm ;-)

**Comment by ctron** [comment]
Ok, I have to admit, it does not look good in the log file!
