### ISSUE TITLE
OBR repository

### ISSUE THREAD

**Issue by maggu2810** [ctron/package-drone#93]
We could create an artifact that create a virtual OBR repository:
https://books.sonatype.com/mcookbook/reference/ch01s09.html

**Comment by ctron** [comment]
Well ... Package Drone already can do an OSGi R5 XML index repository. So if you work with bndtools, that should be sufficient.

An OBR repository could easily be created using a servlet and the OSGi metadata. Like the "r5" adapter servlet.

Of course this process could also speed up using an aspect, which implements channel aggregation and write the index files to the channel cache. This way the servlet only needs to serve the pre-rendered channel cache entry.

**Comment by maggu2810** [comment]
I need at least a valid repository.xml.
Which is the URL to that file of a channel? I do not find that one.

**Comment by ctron** [comment]
So you need OBR or R5?

Maybe you can explain your use case a little bit. I am a child of P2 ;-)

**Comment by ctron** [comment]
Ok, I just saw that the R5 adapter is broken :-(

I will have a look at this on Wednesday. Maybe you have some information on OBR, so I can have a look as well.

**Comment by maggu2810** [comment]
Karaf could use OBR but not p2, so I think it could be useful to support this, too.
I have to read some stuff, first, but OBR seems to try to does the same as p2 but using a different way.
So it would be nice to support both.

* There is also Karaf Cave, that could create an OBR repository (also a proxy of a Maven repo).
* The maven-bundle-plugin could create an OBR index of an existing Maven repo and add this one to the repo.

So, as a Maven plugin could already handle this, I do not know, if there is something to do.

Will wait for your fixed R5 adapter and check if this is working for Karaf out of the box.

**Comment by ctron** [comment]
Ok, the issue with the R5 adapter should be solved. It is not that performant right now, but this can easily be improved.

So by using an URL like `http://server/r5/channel` you should get the index file.

**Comment by maggu2810** [comment]
I tries `obr:url-add http://server/r5/channel` to add the repository to Karaf with installed OBR feature.
This seems to be working.
Using `obr:list` I see the bundles in the repository.
ATM I cannot test if installation is working, but it seems that this is ok for me.
Great stuff!
Could we close this now?

**Comment by ctron** [comment]
I would like to wait for an installation test :wink: 

If this is ok for you!

**Comment by maggu2810** [comment]
Installation with Karaf 4.0.0.M2 failed.
I would like to check if this is a bug in Karaf or in Package Drone using the Karaf OBR proxy and the Package Drone Maven repo with the mvnosgi aspect.
But using the current master shows me an empty Maven repo for my created channel.
... continue in new Issue

**Comment by ctron** [comment]
Did you do any further testing on this one?

**Comment by maggu2810** [comment]
You could trust me, I do not forget this.
But I am very busy at the moment.

**Comment by ctron** [comment]
No problem ... I was just pinging. :wink:

**Comment by maggu2810** [comment]
* I am using the Karaf OBR feature.
* I don't find any information if this works with R5 repositories at all, but it seems to work.
* I can add the R5 repository and list content etc.
* BUT the name field of the bundles are empty
* If I create the repository using another tool, the name is filled.
* If a package does not depend on something, I can install it.
* BUT If I want to install a package that depends on other ones (that are available), it seems that the dependencies could not be resolved correctly.
* If I create the repository using another tool, the dependency are resolved name is filled.

Using Package Drone the name is missing.
```bash
karaf@root()> obr:list
Name | Symbolic Name                 | Version
----------------------------------------------
     | org.apache.commons.io         | 2.2.0
     | org.apache.commons.fileupload | 1.3.1
```

Using another Tool the name is present.
```bash
karaf@root()> obr:list
Name                                  | Symbolic Name                         | Version
----------------------------------------------------------------------------------------------
Apache Commons FileUpload             | org.apache.commons.fileupload         | 1.3.1
Commons IO                            | org.apache.commons.io                 | 2.2.0
```

Using Package Drone the dependencies could not be resolved.
```bash
karaf@root()> obr:deploy org.apache.commons.fileupload
Unsatisfied requirement(s):
---------------------------
   (package=org.apache.commons.io.output)
      null
   (package=org.apache.commons.io)
      null
```

Using another tool the dependencies could be resolved.
```bash
karaf@root()> obr:deploy org.apache.commons.fileupload
Target resource(s):
-------------------
   Apache Commons FileUpload (1.3.1)

Required resource(s):
---------------------
   Commons IO (2.2.0)

Deploying...done.
```

Using Package Drone a package with no dependencies could be installed.
```bash
karaf@root()> obr:deploy org.apache.commons.io
Target resource(s):
-------------------
   null (2.2.0)

Deploying...done.
```

Using Package Drone a package with dependencies (that are already solved) could be installed.
```bash
karaf@root()> obr:deploy org.apache.commons.fileupload
Target resource(s):
-------------------
   null (1.3.1)

Deploying...done.
```

**Comment by maggu2810** [comment]
I uploaded both XML files. Could you have a look at?
https://drive.google.com/open?id=0Bx99QXY8p6gvfmJDZGJTUGh3dFZHclh3dVB0NDJGeldTbE43WDV4Z3lxNmxfYXhoM3pib0k&authuser=0
Is the one a R5 and the other an OBR XML?
What do you think, would a OBR XML aspect something that could be helpful?

**Comment by ctron** [comment]
So it looks like that this is a different repository format indeed. So the Package Drone provides R5, but not OBR.

I guess though that adding OBR would not be a big deal and it should be worth the effort.

**Comment by ctron** [comment]
Can you give me an easy to reproduce setup so that I can test OBR support?

**Comment by maggu2810** [comment]
* Download and extract Karaf 4.0.0 (https://karaf.apache.org/index/community/download.html#Karaf4.0.0)
* Start Karaf (bin/karaf)

* install OBR handling
* feature:install obr

* Install Karaf Cave (OBR repository)
* karaf@root()> feature:repo-add mvn:org.apache.karaf.cave/apache-karaf-cave/3.0.0/xml/features
* karaf@root()> feature:install cave-server
* Use Karaf Cave for the OBR Repository

* create repo
* cave:repository-create my-repository
* populate repository with stuff
* cave:repository-populate my-repository <uri>
* uri could be a single jar (file:/...; http://...; mvn:groupid/artifactid/version) or a whole maven repository (have a look at: https://karaf.apache.org/manual/cave/latest/user-guide/populate-repository.html)
* At any time, you can force the generation and update of the OBR metadata
* cave:repository-update my-repository


* you could show the obr content etc. using OBR commands (see https://karaf.apache.org/manual/latest/users-guide/obr.html)
* e.g. obr:deploy <bsn>
* cave install automatically the cave repos in OBR, you could also add the package-drone OBR (currently R5) XML file as a OBR repo. [obr:url-add]



infos about Cave: https://karaf.apache.org/index/subprojects/cave.html

**Comment by ctron** [comment]
I just pushed a change which provides OBR support.

I did the test with Karaf and it looks good. The "r5" in the URL has to be replaced with "obr". Currently there is no link in the Web UI. I will add this later.
